import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, Jersey_10} from "next/font/google";
import "./globals.css";
import Provider from "./provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const gameFont = Jersey_10({
  variable: '--font-game',
  subsets: ["latin"],
  weight: '400',
})

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className = "dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${gameFont.variable} ${inter.variable}antialiased`}
      >
        <Provider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
        {children}
        </Provider>
      </body>
    </html>
  );
}
